apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicativo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aplicativo
  template:
    metadata:
      labels:
        app: aplicativo
    spec:
      containers:
        - name: aplicativo
          image: Nat250/aplicativo
---
apiVersion: v1
kind: Service
metadata:
  name: aplicativo-clusterip-service
spec:
  selector:
    app: aplicativo
  ports:
    - name: aplicativo
      protocol: TCP
      port: 4000
      targetPort: 4000