apiVersion: v1
kind: Service
metadata:
  name: aplicativo-service
spec:
  type: NodePort
  selector:
    app: aplicativo
  ports:
    - name: aplicativo
    protocol: TCP
    port: 4000
    targetPort: 4000
---
apiVersion: v1
kind: Pod
metadata:
  name: aplicativo
spec:
  containers:
    - name: aplicativo
      image: Nat250/aplicativo
      resources:
        limits:
          memory: 256Mi
          cpu: 1
