apiVersion: v1
kind: Service
metadata:
  name: consulta-service
spec:
  type: NodePort
  selector:
    app: consulta
  ports:
    - name: consulta
    protocol: TCP
    port: 6000
    targetPort: 6000
---
apiVersion: v1
kind: Pod
metadata:
  name: consulta
spec:
  containers:
    - name: consulta
      image: Nat250/consulta
      resources:
        limits:
          memory: 256Mi
          cpu: 1