apiVersion: apps/v1
kind: Deployment
metadata:
  name: keywords-servicos-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keywords-servicos
  template:
    metadata:
      labels:
        app: keywords-servicos
    spec:
      containers:
        - name: keywords-servicos
          image: Nat250/keywords-servicos
---
apiVersion: v1
kind: Service
metadata:
  name: keywords-servicos-clusterip-service
spec:
  selector:
    app: keywords-servicos
  ports:
    - name: keywords-servicos
      protocol: TCP
      port: 5000
      targetPort: 5000