apiVersion: v1
kind: Service
metadata:
  name: keywords-extracao-service
spec:
  type: NodePort
  selector:
    app: keywords-extracao
  ports:
    - name: keywords-extracao
    protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Pod
metadata:
  name: keywords-extracao
spec:
  containers:
    - name: keywords-extracao
      image: Nat250/keywords-extracao
      resources:
        limits:
          memory: 256Mi
          cpu: 1