apiVersion: v1
kind: Service
metadata:
  name: src-service
spec:
  type: NodePort
  selector:
    app: src
  ports:
    - name: src
    protocol: TCP
    port: 7000
    targetPort: 7000
---
apiVersion: v1
kind: Pod
metadata:
  name: src
spec:
  containers:
    - name: src
      image: Nat250/src
      resources:
        limits:
          memory: 256Mi
          cpu: 1